[package]
name = "projectris"
version = "0.1.0"
authors = ["Duncan <bonsairobo@gmail.com>"]
edition = "2018"

[dependencies]
rand = "0.8"
ron = "0.6"
serde = "1.0"

bevy = { version = "0.15", features = ["serialize"] }
